import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>ReciMend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="about row" id={styles.about}>
          <div className="col" id={styles.mainText}>
            <h1 className="text-left" id={styles.mainTitle}>Rec<span id={styles.color}>i</span>Mender</h1>
            <p className="text-left" id={styles.mainDescription}>Don&apos;t know what to cook? ReciMender has you covered!</p>
            <div className="text-center">
             <Link href="/ingredientRecommendation" passhref>
                <button className="btn btn-dark text-center" id={styles.mainButton}>Try it out!</button>
              </Link>
            </div>
            
          </div>
          <div className="col" id={styles.picture}>
          </div>

        </div>
        <div className="sections">
        <div className="exampleCards d-flex justify-content-center">
          <div className="card" id={styles.card}>
              <img src="https://spoonacular.com/cdn/ingredients_500x500/apple.jpg" alt="apple"></img>
              <div className="card-body">
                  <h5 className="card-title">Apple</h5>
              </div>
          </div>
          <div className="card" id={styles.card}>
              <img src="https://spoonacular.com/cdn/ingredients_500x500/pear.jpg" alt="pear"></img>
              <div className="card-body">
                  <h5 className="card-title">Pear</h5>
              </div>
          </div>
          <div className="card" id={styles.card}>
              <img src="https://spoonacular.com/cdn/ingredients_500x500/flour.jpg" alt="flour"></img>
              <div className="card-body">
                  <h5 className="card-title">Flour</h5>
              </div>
          </div>
          <div className="card" id={styles.card}>
              <img src="https://spoonacular.com/cdn/ingredients_500x500/butter.jpg" alt="butter"></img>
              <div className="card-body">
                  <h5 className="card-title">Butter</h5>
              </div>
          </div>
          <div className="card" id={styles.card}>
              <div className="card-body">
                  <h5 className="card-title">ReciMender</h5>
                  <p className="card-text">supports a variety of ingredients!</p>
              </div>
          </div>
      </div>
          {/* Maybe consider using a different colour theme than the ones currently saved in :root */}
        </div>
        <div className="author">
          
        </div>
      </main>
    </>
  )
}
